name: flutter_news_app
description: Flutter News App with NewsApi
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_statusbarcolor: ^0.2.3
  webview_flutter: ^0.3.20+2
  flutter_webview_plugin: ^0.3.11
  share: ^0.6.4
  flutter_launcher_icons: ^0.7.5
  zoom_widget: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.14
  fluttertoast: ^4.0.1
  carousel_slider: ^2.1.0
  photo_view: ^0.9.2
  story_view: ^0.11.0
  cupertino_icons: ^0.1.2
  dio: ^3.0.3
  flutter_bloc: ^0.21.0
  json_serializable: ^3.2.3
  intl: ^0.16.0
  url_launcher: ^5.2.0
  cached_network_image: ^2.0.0-rc

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Tools to write binaries that run builders.
  build_runner: ^1.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    - family: HelveticaL
      fonts:
        - asset: assets/fonts/HelveticaL.ttf
    - family: Caslon
      fonts:
        - asset: assets/fonts/Caslon.otf
    - family: NoeDisplay
      fonts:
        - asset: assets/fonts/NoeDisplay.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy.otf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
